# Generated by Django 2.0.2 on 2018-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='file_file',
            field=models.FileField(default='null', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
