# Generated by Django 2.0.2 on 2018-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180203_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
