# Generated by Django 2.0.2 on 2018-02-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_files_file_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_logo',
        ),
    ]
