# Generated by Django 2.0.2 on 2018-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.IntegerField(default=15158291771114335652),
        ),
    ]
