# Generated by Django 2.0.2 on 2018-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20180210_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.IntegerField(default=6104808169604896049, max_length=255),
        ),
    ]
