# Generated by Django 2.0.2 on 2018-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20180210_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default=15783553383147936828, max_length=255),
        ),
    ]
