# Generated by Django 2.0.2 on 2018-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20180210_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.BigIntegerField(default=3936648312310955468),
        ),
    ]
