# Generated by Django 2.0.2 on 2018-02-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20180210_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='a6f635e62c7b4b0f8ad9416c85819f8a', max_length=255),
        ),
    ]
