# Generated by Django 2.0.2 on 2018-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20180210_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='3f2b4b673c94498997812ade306ba8fc', max_length=500),
        ),
    ]
