# Generated by Django 2.0.2 on 2018-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20180210_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.BigIntegerField(default='4adc3d98803e4ab79537eee8d862808e'),
        ),
    ]
