# Generated by Django 2.0.2 on 2018-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_auto_20180210_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='17606409626380406189', max_length=200, unique=True),
        ),
    ]
