# Generated by Django 2.0.2 on 2018-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20180210_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='0x3', max_length=200, unique=True),
        ),
    ]
