# Generated by Django 2.0.2 on 2018-02-10 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_remove_files_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
