# Generated by Django 2.0.2 on 2018-02-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='<function uuid4 at 0x7f75690e7158>', max_length=200, unique=True),
        ),
    ]
