# Generated by Django 2.0.2 on 2018-02-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_auto_20180210_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_id',
        ),
    ]
