# Generated by Django 2.0.2 on 2018-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0024_files_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='91b456f4790248cebd0e18d9dee40f89', max_length=200, unique=True),
        ),
    ]
