# Generated by Django 2.0.2 on 2018-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_auto_20180210_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='13155073004224089445', max_length=200, unique=True),
        ),
    ]
