# Generated by Django 2.0.2 on 2018-02-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_auto_20180210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='3402598343656482976', max_length=200),
        ),
    ]
