# Generated by Django 2.0.2 on 2018-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_auto_20180211_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='17683856771653387940', max_length=200),
        ),
    ]
