# Generated by Django 2.0.2 on 2018-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_auto_20180211_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='f9f383b929cf4a58820b2a75f05e386b', max_length=200),
        ),
    ]
