# Generated by Django 2.0.2 on 2018-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_auto_20180211_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
