# Generated by Django 2.0.2 on 2018-02-11 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0033_auto_20180211_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=200),
        ),
    ]
