# Generated by Django 2.0.2 on 2018-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0034_auto_20180211_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('Even', 'Even'), ('Odd', 'Odd')], default='Even', max_length=4)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
