# Generated by Django 2.0.2 on 2018-02-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subject',
        ),
    ]
