# Generated by Django 2.0.2 on 2018-02-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0036_remove_subjects_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('Even', 'Even'), ('Odd', 'Odd')], default='Even', max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
