# Generated by Django 2.0.2 on 2018-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0039_auto_20180314_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='faculty',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
