# Generated by Django 2.0.2 on 2018-03-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0040_auto_20180314_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demo.Subject'),
            preserve_default=False,
        ),
    ]
