# Generated by Django 2.0.2 on 2018-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0041_video_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
