# Generated by Django 2.0.2 on 2018-03-18 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0044_auto_20180318_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_file',
            field=models.FileField(default='null', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
