# Generated by Django 2.0.2 on 2018-03-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0045_auto_20180318_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
