# Generated by Django 2.0.2 on 2018-03-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0046_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Exp'),
        ),
    ]
