# Generated by Django 2.0.2 on 2018-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0047_auto_20180328_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='redo',
            field=models.BooleanField(default=False),
        ),
    ]
