# Generated by Django 2.0.2 on 2018-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0048_video_redo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
