# Generated by Django 2.0.2 on 2018-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0050_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
